### ISSUE TITLE
Devicons

### ISSUE THREAD

**Issue by ismay** [ismay/dotfiles#41]
- [x] Brackets show up after sourcing: https://github.com/ryanoasis/vim-devicons/issues/154
- [x] Ignored icon: https://github.com/ryanoasis/vim-devicons/issues/193#issuecomment-281087422
- [ ] Open-close folder icons sometimes don't work correctly: https://github.com/ryanoasis/vim-devicons/issues/194
- [ ] Also, with open/close icons, the text offset is different: https://github.com/ryanoasis/vim-devicons/issues/197
- [ ] When creating new nodes in nerdtree, the icons don't appear (only appear after <kbd>shift</kbd>+<kbd>r</kbd>)
